# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError('Python 2.7 or later required')

# Import the low-level C/C++ module
if __package__ or '.' in __name__:
    from . import _tools
else:
    import _tools

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if name == "thisown":
        return self.this.own(value)
    if name == "this":
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if not static:
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if name == "thisown":
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _tools.delete_SwigPyIterator

    def value(self):
        return _tools.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _tools.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _tools.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _tools.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _tools.SwigPyIterator_equal(self, x)

    def copy(self):
        return _tools.SwigPyIterator_copy(self)

    def next(self):
        return _tools.SwigPyIterator_next(self)

    def __next__(self):
        return _tools.SwigPyIterator___next__(self)

    def previous(self):
        return _tools.SwigPyIterator_previous(self)

    def advance(self, n):
        return _tools.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _tools.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _tools.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _tools.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _tools.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _tools.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _tools.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _tools:
_tools.SwigPyIterator_swigregister(SwigPyIterator)

class vector_double(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _tools.vector_double_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _tools.vector_double___nonzero__(self)

    def __bool__(self):
        return _tools.vector_double___bool__(self)

    def __len__(self):
        return _tools.vector_double___len__(self)

    def __getslice__(self, i, j):
        return _tools.vector_double___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _tools.vector_double___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _tools.vector_double___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _tools.vector_double___delitem__(self, *args)

    def __getitem__(self, *args):
        return _tools.vector_double___getitem__(self, *args)

    def __setitem__(self, *args):
        return _tools.vector_double___setitem__(self, *args)

    def pop(self):
        return _tools.vector_double_pop(self)

    def append(self, x):
        return _tools.vector_double_append(self, x)

    def empty(self):
        return _tools.vector_double_empty(self)

    def size(self):
        return _tools.vector_double_size(self)

    def swap(self, v):
        return _tools.vector_double_swap(self, v)

    def begin(self):
        return _tools.vector_double_begin(self)

    def end(self):
        return _tools.vector_double_end(self)

    def rbegin(self):
        return _tools.vector_double_rbegin(self)

    def rend(self):
        return _tools.vector_double_rend(self)

    def clear(self):
        return _tools.vector_double_clear(self)

    def get_allocator(self):
        return _tools.vector_double_get_allocator(self)

    def pop_back(self):
        return _tools.vector_double_pop_back(self)

    def erase(self, *args):
        return _tools.vector_double_erase(self, *args)

    def __init__(self, *args):
        _tools.vector_double_swiginit(self, _tools.new_vector_double(*args))

    def push_back(self, x):
        return _tools.vector_double_push_back(self, x)

    def front(self):
        return _tools.vector_double_front(self)

    def back(self):
        return _tools.vector_double_back(self)

    def assign(self, n, x):
        return _tools.vector_double_assign(self, n, x)

    def resize(self, *args):
        return _tools.vector_double_resize(self, *args)

    def insert(self, *args):
        return _tools.vector_double_insert(self, *args)

    def reserve(self, n):
        return _tools.vector_double_reserve(self, n)

    def capacity(self):
        return _tools.vector_double_capacity(self)
    __swig_destroy__ = _tools.delete_vector_double

# Register vector_double in _tools:
_tools.vector_double_swigregister(vector_double)

class vector_uchar(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _tools.vector_uchar_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _tools.vector_uchar___nonzero__(self)

    def __bool__(self):
        return _tools.vector_uchar___bool__(self)

    def __len__(self):
        return _tools.vector_uchar___len__(self)

    def __getslice__(self, i, j):
        return _tools.vector_uchar___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _tools.vector_uchar___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _tools.vector_uchar___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _tools.vector_uchar___delitem__(self, *args)

    def __getitem__(self, *args):
        return _tools.vector_uchar___getitem__(self, *args)

    def __setitem__(self, *args):
        return _tools.vector_uchar___setitem__(self, *args)

    def pop(self):
        return _tools.vector_uchar_pop(self)

    def append(self, x):
        return _tools.vector_uchar_append(self, x)

    def empty(self):
        return _tools.vector_uchar_empty(self)

    def size(self):
        return _tools.vector_uchar_size(self)

    def swap(self, v):
        return _tools.vector_uchar_swap(self, v)

    def begin(self):
        return _tools.vector_uchar_begin(self)

    def end(self):
        return _tools.vector_uchar_end(self)

    def rbegin(self):
        return _tools.vector_uchar_rbegin(self)

    def rend(self):
        return _tools.vector_uchar_rend(self)

    def clear(self):
        return _tools.vector_uchar_clear(self)

    def get_allocator(self):
        return _tools.vector_uchar_get_allocator(self)

    def pop_back(self):
        return _tools.vector_uchar_pop_back(self)

    def erase(self, *args):
        return _tools.vector_uchar_erase(self, *args)

    def __init__(self, *args):
        _tools.vector_uchar_swiginit(self, _tools.new_vector_uchar(*args))

    def push_back(self, x):
        return _tools.vector_uchar_push_back(self, x)

    def front(self):
        return _tools.vector_uchar_front(self)

    def back(self):
        return _tools.vector_uchar_back(self)

    def assign(self, n, x):
        return _tools.vector_uchar_assign(self, n, x)

    def resize(self, *args):
        return _tools.vector_uchar_resize(self, *args)

    def insert(self, *args):
        return _tools.vector_uchar_insert(self, *args)

    def reserve(self, n):
        return _tools.vector_uchar_reserve(self, n)

    def capacity(self):
        return _tools.vector_uchar_capacity(self)
    __swig_destroy__ = _tools.delete_vector_uchar

# Register vector_uchar in _tools:
_tools.vector_uchar_swigregister(vector_uchar)

class vector_vector_double(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _tools.vector_vector_double_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _tools.vector_vector_double___nonzero__(self)

    def __bool__(self):
        return _tools.vector_vector_double___bool__(self)

    def __len__(self):
        return _tools.vector_vector_double___len__(self)

    def __getslice__(self, i, j):
        return _tools.vector_vector_double___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _tools.vector_vector_double___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _tools.vector_vector_double___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _tools.vector_vector_double___delitem__(self, *args)

    def __getitem__(self, *args):
        return _tools.vector_vector_double___getitem__(self, *args)

    def __setitem__(self, *args):
        return _tools.vector_vector_double___setitem__(self, *args)

    def pop(self):
        return _tools.vector_vector_double_pop(self)

    def append(self, x):
        return _tools.vector_vector_double_append(self, x)

    def empty(self):
        return _tools.vector_vector_double_empty(self)

    def size(self):
        return _tools.vector_vector_double_size(self)

    def swap(self, v):
        return _tools.vector_vector_double_swap(self, v)

    def begin(self):
        return _tools.vector_vector_double_begin(self)

    def end(self):
        return _tools.vector_vector_double_end(self)

    def rbegin(self):
        return _tools.vector_vector_double_rbegin(self)

    def rend(self):
        return _tools.vector_vector_double_rend(self)

    def clear(self):
        return _tools.vector_vector_double_clear(self)

    def get_allocator(self):
        return _tools.vector_vector_double_get_allocator(self)

    def pop_back(self):
        return _tools.vector_vector_double_pop_back(self)

    def erase(self, *args):
        return _tools.vector_vector_double_erase(self, *args)

    def __init__(self, *args):
        _tools.vector_vector_double_swiginit(self, _tools.new_vector_vector_double(*args))

    def push_back(self, x):
        return _tools.vector_vector_double_push_back(self, x)

    def front(self):
        return _tools.vector_vector_double_front(self)

    def back(self):
        return _tools.vector_vector_double_back(self)

    def assign(self, n, x):
        return _tools.vector_vector_double_assign(self, n, x)

    def resize(self, *args):
        return _tools.vector_vector_double_resize(self, *args)

    def insert(self, *args):
        return _tools.vector_vector_double_insert(self, *args)

    def reserve(self, n):
        return _tools.vector_vector_double_reserve(self, n)

    def capacity(self):
        return _tools.vector_vector_double_capacity(self)
    __swig_destroy__ = _tools.delete_vector_vector_double

# Register vector_vector_double in _tools:
_tools.vector_vector_double_swigregister(vector_vector_double)

class vector_variant(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _tools.vector_variant_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _tools.vector_variant___nonzero__(self)

    def __bool__(self):
        return _tools.vector_variant___bool__(self)

    def __len__(self):
        return _tools.vector_variant___len__(self)

    def __getslice__(self, i, j):
        return _tools.vector_variant___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _tools.vector_variant___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _tools.vector_variant___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _tools.vector_variant___delitem__(self, *args)

    def __getitem__(self, *args):
        return _tools.vector_variant___getitem__(self, *args)

    def __setitem__(self, *args):
        return _tools.vector_variant___setitem__(self, *args)

    def pop(self):
        return _tools.vector_variant_pop(self)

    def append(self, x):
        return _tools.vector_variant_append(self, x)

    def empty(self):
        return _tools.vector_variant_empty(self)

    def size(self):
        return _tools.vector_variant_size(self)

    def swap(self, v):
        return _tools.vector_variant_swap(self, v)

    def begin(self):
        return _tools.vector_variant_begin(self)

    def end(self):
        return _tools.vector_variant_end(self)

    def rbegin(self):
        return _tools.vector_variant_rbegin(self)

    def rend(self):
        return _tools.vector_variant_rend(self)

    def clear(self):
        return _tools.vector_variant_clear(self)

    def get_allocator(self):
        return _tools.vector_variant_get_allocator(self)

    def pop_back(self):
        return _tools.vector_variant_pop_back(self)

    def erase(self, *args):
        return _tools.vector_variant_erase(self, *args)

    def __init__(self, *args):
        _tools.vector_variant_swiginit(self, _tools.new_vector_variant(*args))

    def push_back(self, x):
        return _tools.vector_variant_push_back(self, x)

    def front(self):
        return _tools.vector_variant_front(self)

    def back(self):
        return _tools.vector_variant_back(self)

    def assign(self, n, x):
        return _tools.vector_variant_assign(self, n, x)

    def resize(self, *args):
        return _tools.vector_variant_resize(self, *args)

    def insert(self, *args):
        return _tools.vector_variant_insert(self, *args)

    def reserve(self, n):
        return _tools.vector_variant_reserve(self, n)

    def capacity(self):
        return _tools.vector_variant_capacity(self)
    __swig_destroy__ = _tools.delete_vector_variant

# Register vector_variant in _tools:
_tools.vector_variant_swigregister(vector_variant)

class match(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    pos = property(_tools.match_pos_get, _tools.match_pos_set)
    score = property(_tools.match_score_get, _tools.match_score_set)

    def __init__(self):
        _tools.match_swiginit(self, _tools.new_match())
    __swig_destroy__ = _tools.delete_match

# Register match in _tools:
_tools.match_swigregister(match)

class variant(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    start_pos = property(_tools.variant_start_pos_get, _tools.variant_start_pos_set)
    end_pos = property(_tools.variant_end_pos_get, _tools.variant_end_pos_set)
    modified_seq = property(_tools.variant_modified_seq_get, _tools.variant_modified_seq_set)

    def __lt__(self, rhs):
        return _tools.variant___lt__(self, rhs)

    def __init__(self, *args):
        _tools.variant_swiginit(self, _tools.new_variant(*args))
    __swig_destroy__ = _tools.delete_variant

# Register variant in _tools:
_tools.variant_swigregister(variant)

class match_with_variant(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    pos = property(_tools.match_with_variant_pos_get, _tools.match_with_variant_pos_set)
    score = property(_tools.match_with_variant_score_get, _tools.match_with_variant_score_set)
    variants = property(_tools.match_with_variant_variants_get, _tools.match_with_variant_variants_set)

    def __init__(self):
        _tools.match_with_variant_swiginit(self, _tools.new_match_with_variant())
    __swig_destroy__ = _tools.delete_match_with_variant

# Register match_with_variant in _tools:
_tools.match_with_variant_swigregister(match_with_variant)


def flat_bg(alphabet_size):
    return _tools.flat_bg(alphabet_size)

def bg_from_sequence_dna(seq, ps):
    return _tools.bg_from_sequence_dna(seq, ps)

def snp_variants(seq):
    return _tools.snp_variants(seq)

def min_delta(mat):
    return _tools.min_delta(mat)

def max_score(*args):
    return _tools.max_score(*args)

def min_score(*args):
    return _tools.min_score(*args)

def threshold_from_p(*args):
    return _tools.threshold_from_p(*args)

def threshold_from_p_with_precision(*args):
    return _tools.threshold_from_p_with_precision(*args)

def reverse_complement(*args):
    return _tools.reverse_complement(*args)

def log_odds(*args):
    return _tools.log_odds(*args)

cvar = _tools.cvar
DEFAULT_DP_PRECISION = cvar.DEFAULT_DP_PRECISION

